#!/bin/bash
#
# Claude Local Memory Server - Docker Installation Script
#
# For systemd/LXC deployment, use install-systemd.sh instead.
#
# Usage:
#   ./scripts/install-docker.sh
#
# Options:
#   --port PORT         HTTP port (default: 8420)
#   --api-key KEY       Set API key for authentication (generated if omitted)
#   --no-start          Build only, don't start the container
#

set -e

# --- Configuration ---
PORT=8420
API_KEY=""
START_CONTAINER=true

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# --- Parse arguments ---
while [[ $# -gt 0 ]]; do
    case $1 in
        --port)
            PORT="$2"
            shift 2
            ;;
        --api-key)
            API_KEY="$2"
            shift 2
            ;;
        --no-start)
            START_CONTAINER=false
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --port PORT         HTTP port (default: 8420)"
            echo "  --api-key KEY       Set API key for authentication (generated if omitted)"
            echo "  --no-start          Build only, don't start the container"
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            exit 1
            ;;
    esac
done

# --- Check Docker ---
if ! command -v docker &> /dev/null; then
    log_error "Docker is not installed. Please install Docker first:"
    echo "  https://docs.docker.com/get-docker/"
    exit 1
fi

# Check if docker compose is available (v2 style)
if docker compose version &> /dev/null; then
    COMPOSE_CMD="docker compose"
elif command -v docker-compose &> /dev/null; then
    COMPOSE_CMD="docker-compose"
else
    log_error "Docker Compose is not installed. Please install Docker Compose:"
    echo "  https://docs.docker.com/compose/install/"
    exit 1
fi

log_info "Using: $COMPOSE_CMD"

# --- Find project root ---
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

if [[ ! -f "$PROJECT_ROOT/docker-compose.yml" ]]; then
    log_error "docker-compose.yml not found in $PROJECT_ROOT"
    exit 1
fi

cd "$PROJECT_ROOT"

# --- Generate API key if not provided ---
if [[ -z "$API_KEY" ]]; then
    API_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || \
              openssl rand -base64 32 | tr -d '/+=' | head -c 32)
    log_info "Generated API key: $API_KEY"
    log_warn "Save this key! You'll need it to configure clients."
fi

# --- Create .env file ---
log_info "Creating .env file..."
cat > .env << EOF
# Claude Local Memory Server - Docker Configuration
# Generated by install-docker.sh

MEMORY_API_KEY=$API_KEY
PORT=$PORT
EOF

chmod 600 .env
log_info "Environment saved to .env"

# --- Build the image ---
log_info "Building Docker image..."
$COMPOSE_CMD build

if [[ "$START_CONTAINER" == true ]]; then
    # --- Start the container ---
    log_info "Starting container..."
    $COMPOSE_CMD up -d

    # Wait for health check
    log_info "Waiting for server to be ready..."
    sleep 3

    # Check if running
    if $COMPOSE_CMD ps | grep -q "running\|Up"; then
        log_info "Container is running"
    else
        log_error "Container failed to start. Check logs with: $COMPOSE_CMD logs"
        exit 1
    fi
fi

# --- Get host IP ---
HOST_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")

# --- Print summary ---
echo ""
echo "========================================"
echo "  Claude Local Memory Server (Docker)"
echo "========================================"
echo ""
echo "  Port:     $PORT"
echo "  API Key:  $API_KEY"
echo ""
echo "  Docker commands:"
echo "    $COMPOSE_CMD ps          # Status"
echo "    $COMPOSE_CMD logs -f     # View logs"
echo "    $COMPOSE_CMD down        # Stop"
echo "    $COMPOSE_CMD up -d       # Start"
echo ""
echo "  Test the server:"
echo "    curl http://localhost:$PORT/health"
echo "    curl http://localhost:$PORT/stats -H 'X-API-Key: $API_KEY'"
echo ""
echo "  Client configuration:"
echo "    MEMORY_SERVER=http://$HOST_IP:$PORT"
echo "    MEMORY_API_KEY=$API_KEY"
echo ""
echo "========================================"

# --- Save client config ---
cat > client-config.txt << EOF
# Claude Local Memory Server - Client Configuration
# Copy this to your development machines

MEMORY_SERVER=http://$HOST_IP:$PORT
MEMORY_API_KEY=$API_KEY

# Claude Code MCP config (replace CLIENT_NAME with e.g. 'laptop', 'desktop'):
claude mcp add-json "memory" '{
  "command": "python",
  "args": ["-m", "claude_memory.cli", "client"],
  "env": {
    "MEMORY_SERVER": "http://$HOST_IP:$PORT",
    "MEMORY_API_KEY": "$API_KEY",
    "MEMORY_CLIENT_ID": "CLIENT_NAME"
  }
}'
EOF

log_info "Client config saved to: client-config.txt"
